// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KTGK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KTGK.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "21DTHA1",
                            ImagePath = "/images/grades/lop1.png"
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "21DTHA2",
                            ImagePath = "/images/grades/lop2.png"
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "21DTHA3",
                            ImagePath = "/images/grades/lop3.png"
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "21DTHA4",
                            ImagePath = "/images/grades/lop4.png"
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "21DTHA5",
                            ImagePath = "/images/grades/lop4.png"
                        });
                });

            modelBuilder.Entity("KTGK.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("GradeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Khuyên",
                            GradeId = 1,
                            LastName = "Bùi"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Toàn",
                            GradeId = 1,
                            LastName = "Nguyễn"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Hương",
                            GradeId = 2,
                            LastName = "Trần"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Quang",
                            GradeId = 2,
                            LastName = "Lê"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "Mai",
                            GradeId = 3,
                            LastName = "Phạm"
                        },
                        new
                        {
                            StudentId = 6,
                            FirstName = "Long",
                            GradeId = 3,
                            LastName = "Đỗ"
                        },
                        new
                        {
                            StudentId = 7,
                            FirstName = "Thanh",
                            GradeId = 4,
                            LastName = "Hoàng"
                        },
                        new
                        {
                            StudentId = 8,
                            FirstName = "Vân",
                            GradeId = 4,
                            LastName = "Ngô"
                        },
                        new
                        {
                            StudentId = 9,
                            FirstName = "Minh",
                            GradeId = 5,
                            LastName = "Vũ"
                        },
                        new
                        {
                            StudentId = 10,
                            FirstName = "Anh",
                            GradeId = 5,
                            LastName = "Đặng"
                        });
                });

            modelBuilder.Entity("KTGK.Models.Student", b =>
                {
                    b.HasOne("KTGK.Models.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("KTGK.Models.Grade", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
